{{- $helixVersion := "23.10"}}
{{- $helixArch := "x86_64"}}
{{- $helixOS := "linux"}}
{{- $helixPackageName := printf "helix-%s-%s-%s" $helixVersion $helixArch $helixOS }}

{{- $helixArchiveUrl := printf "https://github.com/helix-editor/helix/releases/download/%s/%s.tar.xz" $helixVersion $helixPackageName -}}

[".local/bin/hx"]
    type = "archive-file"
    executable = true
    path = {{printf "%s/hx" $helixPackageName | quote}}
    url = {{ $helixArchiveUrl | quote }}

[".config/helix"]
    type = "archive"
    stripComponents = 1
    include = [
        {{printf "%s/runtime/**" $helixPackageName | quote}},
    ]
    url = {{ $helixArchiveUrl | quote }}
