[".local/bin/terraform-ls"]
  type = "archive-file"
  url = "https://releases.hashicorp.com/terraform-ls/0.32.3/terraform-ls_0.32.3_{{.chezmoi.os}}_{{.chezmoi.arch}}.zip"
  path = "terraform-ls"

{{- if eq .chezmoi.arch "amd64"}}
[".local/bin/marksman"]
  type = "file"
  executable = true
  url = "https://github.com/artempyanykh/marksman/releases/download/2023-12-09/marksman-{{.chezmoi.os}}-x64"
{{end}}
