{{- if eq .chezmoi.os "linux"}}
[".local/bin/nvim-bin"]
    type = "archive"
    url = "https://github.com/neovim/neovim/releases/download/v0.9.4/nvim-linux64.tar.gz"
    stripComponents = 1
{{end}}

[".config/nvim"]
    type = "archive"
    url = "https://github.com/LazyVim/starter/archive/refs/heads/main.tar.gz"
    stripComponents = 1
    exclude = ["**/options.lua"]
