[".zsh/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/bin/devpod"]
    type = "file"
    executable = true
    {{ if and (eq .chezmoi.os "linux") (eq .chezmoi.arch "amd64") -}}
    url = "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64"
    {{ else if and (eq .chezmoi.os "linux") (eq .chezmoi.arch "arm64") -}}
    url = "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-arm64"
    {{ else if and (eq .chezmoi.os "darwin") (eq .chezmoi.arch "arm64") -}}
    url = "https://github.com/loft-sh/devpod/releases/latest/download/devpod-darwin-amd64"
    {{ else if and (eq .chezmoi.os "darwin") (eq .chezmoi.arch "arm64") -}}
    url = "https://github.com/loft-sh/devpod/releases/latest/download/devpod-darwin-arm64"
    {{- end }}

{{if (and .chezmoi.osRelease (eq .chezmoi.osRelease.id "fedora")) -}}
[".fonts"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip"
    exact = true
    refreshPeriod = "168h"
{{- end}}

{{ if eq .chezmoi.os "linux" -}}
[".local/bin/hx"]
    type = "file"
    executable = true
    filter.command = "tar"
    filter.args = ["--xz", "--to-stdout", "--extract", "--file=-", "helix-23.10-x86_64-linux/hx"]
    url = "https://github.com/helix-editor/helix/releases/download/23.10/helix-23.10-x86_64-linux.tar.xz"

[".config/helix"]
    type = "archive"
    stripComponents = 1
    include = [
        "helix-23.10-x86_64-linux/runtime/**",
        "helix-23.10-x86_64-linux/contrib/**",
    ]
    url = "https://github.com/helix-editor/helix/releases/download/23.10/helix-23.10-x86_64-linux.tar.xz"

[".local/bin/starship"]
    type = "file"
    executable = true
    filter.command = "tar"
    filter.args = ["--gzip", "--to-stdout", "--extract", "--file=-", "starship"]
    {{ if eq .chezmoi.arch "arm64" -}}
    url = "https://github.com/starship/starship/releases/latest/download/starship-aarch64-unknown-linux-musl.tar.gz"
    {{- else }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
    {{- end }}

[".local/bin/nvim-bin"]
    type = "archive"
    url = "https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz"
    stripComponents = 1

[".local/bin/task"]
    type = "file"
    executable = true
    filter.command = "tar"
    filter.args = ["--gzip", "--to-stdout", "--extract", "--file=-", "task"]
    url = "https://github.com/go-task/task/releases/latest/download/task_linux_amd64.tar.gz"

[".zsh/completion/_task"]
    type = "file"
    executable = true
    filter.command = "tar"
    filter.args = ["--gzip", "--to-stdout", "--extract", "--file=-", "completion/zsh/_task"]
    url = "https://github.com/go-task/task/releases/latest/download/task_linux_amd64.tar.gz"

[".local/bin/zellij"]
    type = "file"
    executable = true
    filter.command = "tar"
    filter.args = ["--gzip", "--to-stdout", "--extract", "--file=-", "zellij"]
    url = "https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz"

[".local/bin/node-bin"]
    type = "archive"
    url = "https://nodejs.org/download/release/v16.20.0/node-v16.20.0-linux-x64.tar.gz"
    stripComponents = 1
    checksum.sha256 = "7abc0e558fa3b3c4cc0fd3c7fa5dbe61500ba7213f5e87ed560c65a733c6a5c4"
{{- end}}

[".config/nvim"]
    type = "archive"
    url = "https://github.com/LazyVim/starter/archive/refs/heads/main.tar.gz"
    stripComponents = 1
    exclude = ["**/options.lua"]

{{if eq .chezmoi.os "darwin"}}
[".local/bin"]
    type = "archive"
    url = "https://github.com/zellij-org/zellij/releases/latest/download/zellij-aarch64-apple-darwin.tar.gz"
    checksum.sha256 = "3de544f0cdae394b851bd0d2da13d3d7a841f7bddbc0a78ca8e4c9aea06bab64"
{{- end}}

