[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

{{ if (and .chezmoi.osRelease (eq .chezmoi.osRelease.id "fedora")) -}}
[".fonts"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip"
    exact = true
    refreshPeriod = "168h"
{{- end }}

{{ if eq .chezmoi.arch "amd64" -}}
[".local/bin"]
    type = "archive"
    url = "https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.tar.gz"
    include = ["nvim-linux64/bin/nvim"]
    checksum.sha256 = "58ac03b345e8675e13322f8c7135906ce26a1ca7a87d041344d64b207be7bedf"
    stripComponents = 2
{{- end }}

[".config/nvim"]
    type = "archive"
    url = "https://github.com/AstroNvim/AstroNvim/archive/refs/tags/v2.11.8.zip"
    exact = true
    stripComponents = 1
