[tools]
bat = "latest"
btop = "latest"
chezmoi = "latest"
doggo = "latest"
fd = "latest"
fzf = "latest"
lazydocker = "latest"
lazygit = "latest"
eza = "latest"
neovim = "0.11.4"
node = "23.11.0"
ripgrep = "latest"
starship = "1.23.0"
"ubi:nushell/nushell" = { version = "0.108.0", exe = "nu" }
yazi = "latest"
zellij = "0.43.1"
zoxide = "latest"
