# Regular tools for all environments
[tools]
bat = "latest"
btop = "latest"
chezmoi = "latest"
doggo = "latest"
fd = "latest"
fzf = "latest"
lazydocker = "latest"
lazygit = "latest"
eza = "latest"
neovim = "0.11.4"
node = "23.11.0"
ripgrep = "latest"
starship = "1.23.0"
"ubi:nushell/nushell" = { version = "0.108.0", exe = "nu" }
yazi = "latest"
zellij = "0.43.1"
zoxide = "latest"

{{- if eq .containerName "arch-toolbox" }}
# Arch toolbox specific tools
go = "latest"
rust = "latest"
{{- end }}

# Tasks
[tasks.distrobox-update]
description = "Update all packages in distrobox"
run = '''
{{- if eq .containerName "arch-toolbox" }}
yay -Syu --noconfirm
{{- else }}
echo "Not in a configured distrobox"
{{- end }}
'''
