# Regular tools for all environments
[tools]
age = "latest"
aichat = "latest"
bat = "latest"
btop = "latest"
cheat = "latest"
chezmoi = "latest"
claude-squad = "latest"
code = "latest"
doggo = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
glow = "latest"
k9s = "latest"
kind = "latest"
kustomize = "latest"
kubectl = "latest"
kubectx = "latest"
lazydocker = "latest"
lazygit = "latest"
eza = "latest"
neovim = "0.11.4"
node = "23.11.0"
opencode = "latest"
ripgrep = "latest"
starship = "1.23.0"
yazi = "latest"
zellij = "0.43.1"
zoxide = "latest"
python = "latest"
uv = "latest"
