[tools]
neovim = "0.11.1"
ripgrep = "latest"
zoxide = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
direnv = "latest"
xh = "latest"
zellij = "latest"
starship = "latest"
chezmoi = "latest"
