# Regular tools for all environments
[tools]
age = "latest"
bat = "latest"
btop = "latest"
chezmoi = "latest"
direnv = "latest"
docker-compose = "latest"
doggo = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
lazygit = "latest"
navi = "latest"
neovim = "0.11.4"
node = "22.21.0"
opencode = "latest"
python = "3.12.12"
ripgrep = "latest"
starship = "1.23.0"
uv = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
