[tools]
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
neovim = "0.11.1"
node = "23.11.0"
ripgrep = "latest"
starship = "latest"
"ubi:sst/opencode" = "latest"
xh = "latest"
zellij = "latest"
zoxide = "latest"
