[tools]
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
neovim = "0.11.1"
node = "23.11.0"
ripgrep = "latest"
starship = "latest"
"ubi:charmbracelet/crush" = "0.2.1"
"ubi:loft-sh/devpod" = { version = "0.7.0-alpha.34", matching = "devpod-", rename_exe = "devpod" }
xh = "latest"
zellij = "latest"
zoxide = "latest"
