# Regular tools for all environments
[tools]
age = "latest"
bat = "latest"
btop = "latest"
chezmoi = "latest"
direnv = "latest"
doggo = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
lazygit = "latest"
neovim = "0.11.4"
node = "23.11.0"
python = "latest"
ripgrep = "latest"
starship = "1.23.0"
uv = "latest"
zellij = "latest"
zoxide = "latest"
