[tools]
neovim = "0.10.3"
ripgrep = "latest"
zoxide = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
direnv = "latest"
xh = "latest"
zellij = "latest"
starship = "latest"
node = "latest"
chezmoi = "latest"
