# Generated by theme-switch — do not edit by hand.
# Sourced from ~/.config/shell/30-fzf.sh (or equivalent) to apply theme colors.

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} \
  --color=fg:@fg@,bg:@bg@,hl:@accent@ \
  --color=fg+:@fg@,bg+:@bg_sel@,hl+:@accent@ \
  --color=info:@yellow@,prompt:@accent@,pointer:@accent@ \
  --color=marker:@green@,spinner:@magenta@,header:@cyan@ \
  --color=border:@border@"

export BAT_THEME="@bat_theme@"
