-- Generated by theme-switch -- do not edit by hand.
-- Required from ~/.config/nvim/lua/config/options.lua (or init.lua) to set
-- the colorscheme on startup. Plugins for both gruvbox and rose-pine must
-- be installed via LazyVim (lazy.nvim spec) for the colorscheme call to work.

vim.opt.background = "@nvim_background@"
local ok, err = pcall(vim.cmd.colorscheme, "@nvim_colorscheme@")
if not ok then
  vim.notify("theme: colorscheme @nvim_colorscheme@ failed: " .. tostring(err), vim.log.levels.WARN)
end
