"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$kubernetes\
$aws\
$pulumi\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break\
$container\
$hostname\
$sudo\
$cmd_duration\
$character"""

palette = 'gruvbox_dark'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Bluefin = "󰌽"
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#FFFFFF bg:color_bg3)]($style)'

[conda]
symbol = "  "
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#FFFFFF bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:color_bg1"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[palettes.gruvbox_dark]
color_fg0 = '#FFFFFF'
color_bg1 = '#545464'
color_bg3 = '#597b75'
color_blue = '#4d699b'
color_aqua = '#6f894e'
color_green = '#6f894e'
color_orange = '#cc6d00'
color_purple = '#b35b79'
color_red = '#c84053'
color_yellow = '#b09250'

# Custom config from here on
[container]
style = "bg:color_bg1 fg:color_fg0"
format = "[](color_bg1)[$symbol $name]($style)[ ](fg:color_bg1)"

[hostname]
ssh_symbol = "❮=❯ "
style = "bg:color_bg1 fg:color_fg0"
format = "[](color_bg1)[$ssh_symbol$hostname]($style)[ ](fg:color_bg1)"

[sudo]
disabled = false
symbol = "⚠️"
style = "bg:color_bg1 fg:color_fg0"
format = "[](color_bg1)[$symbol]($style)[ ](fg:color_bg1)"

[gcloud]
disabled = true

[aws]
style = "bg:color_bg3 fg:color_fg0"
format = '[ on AWS ($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
symbol = '☸'
format = '[[ $symbol( $context \($namespace\)) ](fg:color_fg0 bg:color_bg3)]($style)'
disabled = false

[pulumi]
format = '[[ $symbol( $stack ) ](fg:color_fg0 bg:color_bg3)]($style)'
